DB/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import store_post,dashboard_embedd
app_name = 'DB'
urlpatterns = [
    path("pushed/",store_post,name='post'),
    path("Dashboard/",dashboard_embedd,name='dashboard')
]

Users/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.contrib.auth.views import LoginView,LogoutView
app_name = 'users'
urlpatterns = [
    path("",views.firstpage,name='first'),
    path("accounts/Register",views.Register,name='Register'),
    # path("accounts/",include('django.contrib.auth.urls'))
    path("accounts/login/",LoginView.as_view(template_name='registration/login.html'),name='login'),
    path("accounts/logout/",LogoutView.as_view(next_page='users:login'),name='logout'),
    path("successlogin/",views.Sucesslogin,name='success'),
    path("successlogout/",views.Successlogout,name='successl'),
    path('accounts/profile',views.profile,name='profile'),
    path('accounts/ScrapedHistory',views.scrapeddata,name='scrapedata')
    
  
]

scrape/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'scrape'
urlpatterns = [
    path("",views.home,name='home'),
    path("data/",views.data,name='data'),
    path('pushing/',views.statistics,name='sts'),
    path('Scrapedinfo/',views.MoreInfomation,name='info')

    # path('dashboard/',views.dash,name='dash')
    
]
 

yt/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("Home/",include('scrape.urls',namespace='scrape')),
    path("db/",include('DB.urls', namespace='DB')),
    path("",include('Users.urls',namespace='users'))
    

]

scrape/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class store(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    links = models.URLField()
    Time = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ['-Time']
    
    def __str__(self):
        return f"{self.user} - {self.links}"

scrape/forms.py
from django.forms import ModelForm
from .models import store
class storeroom(ModelForm):
    class Meta:
        model = store
        fields = ['links']

    

scrape/views.py
from django.shortcuts import render,HttpResponse,redirect
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from tqdm import tqdm
import os
import time
from googleapiclient.discovery import build
import psycopg2
from django.contrib import messages
from .models import store
from .forms import storeroom
import json
from django.utils import timezone
from django.contrib.auth.decorators import login_required

# Create your views here.
#2nd Set your driver
c_op = Options()
c_op.add_argument("--headless") #without chrome
c_op.add_argument("--disable-gpu") # no acceleration
c_op.add_argument("--window-size=1920,1080") # set window size
c_op.add_argument("--disable-blink-features=AutomationControlled") # bypass robotdetection
chrome_service = Service(r"C:\Users\lipun\OneDrive\Documents\chromedriver-win64\chromedriver-win64\chromedriver.exe") #path
driver = webdriver.Chrome(service=chrome_service,options=c_op)
  

   
#CONNECT TO DB
# def connectdb(request):
#    return psycopg2.connect(**DB) # **it will unpack dict to individual components!! dont directly use DB
# def display_links(request):
#     if request.method == 'POST' and 'hist' in request.POST:
#         l = store.objects.filter(user=request.user)
#         context = {
#             'l2':l,
#             'show':True
#         }
#         return render(request,"scrape/home.html",context)
#     return render(request,"scrape/home.html")
@login_required
def statistics(request):
    lst = []
    if(request.method=='POST'):
        f = store.objects.filter(user=request.user).order_by("-Time").first()
        if f:
              
          strfile = f.links
          link_id = strfile.split("=")[-1]
          yts = build("youtube","v3",developerKey="AIzaSyA6IX_Rvr2CQjNiDJ4aAuEmER6Z0PkDSN4") 
          res = yts.videos().list(
              part = "snippet,statistics",
              id = link_id
          )
          resp = res.execute()
          try:
               Likes = int(resp['items'][0]['statistics']['likeCount'])
               Views = int(resp["items"][0]['statistics']['viewCount'])
               CommentsCount = int(resp['items'][0]['statistics']['commentCount'])
               channel_id = resp['items'][0]['snippet']['channelId']
               Title = resp['items'][0]['snippet']['title']
               #about is imp later on!!
          except:
              LIKES = None
              Views = None
              CommentsCount=None
          res1 = yts.channels().list(
               part = 'snippet,statistics',
               id = channel_id 
              )
          resp1 = res1.execute()
          try:
              subs = int(resp1['items'][0]['statistics']['subscriberCount'])
          except:
              subs = None
          #created = timezone.now()
          lst.append([Title,Likes,Views,CommentsCount,subs])
          df1 =  pd.DataFrame(lst,columns=['Title','Likes','Views','CommentsCount','Subs'])

          df_json = df1.to_json(orient="records")
          request.session['df2'] = df_json
          return redirect("DB:post")
        else:
            messages.error(request," No links Found! ")
            return redirect("scrape:data")             
    return render(request,"scrape/home.html")        
          
          
                    


          

# def dash(request):
#     return render(request,'scrape/dashboards.html')  
    
def data(request):
    return render(request,"scrape/data.html")

@login_required
def home(request):
    if(request.method=='POST'):
      links = request.POST.get('links')
      form = storeroom(request.POST)
      if form.is_valid():
          scraped_link = form.save(commit=False)
          scraped_link.user = request.user
          scraped_link.save()
      
 
    
      if 'watch?v' in links:

         driver.get(str(links))
         video = driver.find_element(By.TAG_NAME,'video')
         driver.execute_script("document.querySelector('video').pause();") #pausing !

         for i in tqdm(range(0,5000,100)):
            driver.execute_script(f"window.scrollTo(0,{str(i)})")
            time.sleep(.1)
         soup = BeautifulSoup(driver.page_source,"html.parser")
         vid_id = links.split("=")[-1] 
         yt = build('youtube','v3',developerKey="AIzaSyA6IX_Rvr2CQjNiDJ4aAuEmER6Z0PkDSN4")
         #api request to get videos details
         r = yt.videos().list(
            part = "statistics,snippet",
            id = vid_id
         )
         response = r.execute()
         try:
            likes = int(response["items"][0]['statistics']['likeCount'])
            views = int(response["items"][0]['statistics']['viewCount'])
            Published_at =response['items'][0]['snippet']['publishedAt']
            Description = response['items'][0]['snippet']['description']
            AudioLang = response['items'][0]['snippet']['defaultAudioLanguage']
            video_thumbnail = response['items'][0]['snippet']['thumbnails']['standard']['url']
            channel_id = response['items'][0]['snippet']['channelId']

         except:
            print("invalid id")
         al_lst = []
         al_st = []
        #  #channel INFO
        #  request_channel = yt.channels().list(
        #     part = 'snippet,statistics',
        #     id = channel_id
        #  )
        #  response_channel = request_channel.execute()
        #  try:
        #     channel_Published_at = response_channel['items'][0]['snippet']['publishedAt']
        #     Description_channel = response_channel['items'][0]['snippet']['description']
        #     Channel_Name = response_channel['items'][0]['snippet']['title']
        #     Thumbnail = response_channel['items'][0]['snippet']['thumbnails']['medium']['url']
        #     Country = response_channel['items'][0]['snippet']['country']
            


        #  except:
        #     print("invalid channel id")



         title, channel_name, home_channel_link = None,None,None
         #Analysis On Scraping data (its increases time But worth it for Practicing!)
         for div in soup.find_all("ytd-watch-flexy"):
                 title = div.find_all("yt-formatted-string",class_="style-scope ytd-watch-metadata")[0].text
                 channel_name = div.find("a",class_="yt-simple-endpoint style-scope yt-formatted-string").text
                 home_channel_link = "https://www.youtube.com"+div.find("a",class_="yt-simple-endpoint style-scope yt-formatted-string").get("href")
                 subscribers = div.find("yt-formatted-string",class_="style-scope ytd-video-owner-renderer").text
                 s = subscribers.split(" ")[0]
                 if(s[-1]=='M'):
                     subscribers = s.replace("M","")
                     subscribers = int(float(subscribers)*1000000)
                 elif(s[-1]=='B'):
                     subscribers = s.replace("B","")
                     subscribers = int(float(subscribers)*1000000000)
                 elif(s[-1]=='K'):
                     subscribers = s.replace("K","")
                     subscribers = int(float(subscribers)*1000)
                 about = div.find_all("span",class_="yt-core-attributed-string--link-inherit-color")[0].text
                 for i in soup.find_all("span",class_="style-scope yt-formatted-string"):
                     try:
                         if type(int(i.text.replace(",","")))==int:
                              comments = i.text
                              break
                     except:
                            pass
                 comments = comments.replace(",","")
                 comments = int(comments)
                 ls = []
                 ig = []
                 twi = []
                 face = []
                 for i in div.find_all("a"):
                        ls.append(i.get("href"))
                 for i in ls:
                     try:
                        if "instagram.com" in str(i):
                           ig.append(i)
                           break
                        
                     except:
                           ig.append(np.nan)
                 for i in ls:
                     try:
                        if "twitter.com" in str(i):
                            twi.append(i)
                            break
                        
                     except:
                            twi.append(np.nan)

                 for i in ls:
                     try:
                        if "facebook.com" in str(i):
                            face.append(i)
                            break
                          
                     except:
                            face.append(np.nan)
                 ig = "".join(ig)
                 twi = "".join(twi)
                 face = "".join(face)
                 lll = []
                 About = []
                 alternative_link = []
                 for spans in div.find_all('yt-attributed-string',class_ = "style-scope ytd-text-inline-expander"):
                     for i in spans.find_all("span"):
                        lll.append(i.text)
                     abt = " ".join(lll).split(" ")
                 for i in abt:
                     if "https" in i:
                        alternative_link.append(i)
                     if "http" in i:
                        alternative_link.append(i)
                     if "https" and "http" not in i:
                        About.append(i)
                 # alternative_link="".join(alternative_link)
                 About = " ".join(About)
         
         al_st.append([title,likes,views,comments,subscribers,vid_id])
        #  YVdfst = pd.DataFrame(al_st,columns=["Title",'Likes','Views','Comments','Subscribers',"video_id"])
         

scrape/templates/scrape/dashboards.html
<!DOCTYPE html>
<html lang="ar" dir="ltr">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.rtl.min.css"
      integrity="sha384-q8+l9TmX3RaSz3HKGBmqP2u5MkgeN7HrfOJBLcTgZsQsbrx8WqqxdA5PuwUV9WIx"
      crossorigin="anonymous"
    />

    <title>DashBoard</title>
    <script src="https://unpkg.com/@superset-ui/embedded-sdk"></script>
  </head>
  <body>
    
    <center><h1>DashBoard</h1></center>
    <hr />
    <div id="superset" style="height:90vh;">

    </div>
    <script>
      const token = "{{token|safe}}";
      window.supersetEmbeddedSdk.embedDashboard({
        id: "0ff0e534-c5c0-4efd-a460-7a84d4bb292c",
        supersetDomain: "http://192.168.29.56:8088",  
        mountPoint: document.getElementById("superset"),
        fetchGuestToken: () => Promise.resolve(token),
        dashboardUiConfig: {
            hideTitle: true,
            hideChartControls: true,
        },
      });
    </script>
   
      
     
    
    <br />

    <form action="{% url 'scrape:home' %}">
      {% csrf_token %}
      <button
        onclick="window.location.href='{% url 'scrape:home' %}'"
        type="submit"
        class="btn btn-outline-info"
      >
        Home Page
      </button>
    </form>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq"
      crossorigin="anonymous"
    ></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.min.js" integrity="sha384-VQqxDN0EQCkWoxt/0vsQvZswzTHUVOImccYmSyhJTp7kGtPed0Qcx8rK9h9YEgx+" crossorigin="anonymous"></script>
    -->
  </body>
</html>

scrape/templates/scrape/data.html
{% extends 'scrape/main.html' %} 
{% block content %} 
{% if message %} 
{% for message in messages%}
<p style="text-align: center;margin-left: 29%;
    margin-right: 29%;" class="alert alert-{{message.tags}}">{{message}}</p>
{%endfor%} 
{% endif %}



<br />
<div class="card text-center" style="margin-left: 10%;margin-right: 10%;margin-top: -2%;">
  <div class="card-header" style="background-color: oldlace;">
    <h1><strong>Scraped Data</strong></h1>
  </div>
  <div class="card-body">
    <table class="table table-info table-striped">
      <tr class="table-dark">
        <td><strong>Title</strong></td>
        <td><strong>Likes</strong></td>
        <td><strong>Views</strong></td>
        <td><strong>Comments</strong></td>
        <td><strong>Subscribers</strong></td>
      </tr>
      {% for i in tohtml%}
      <tr>
        <td><strong>{{i.0}}</strong></td>
        <td><strong>{{i.1}}</strong></td>
        <td><strong>{{i.2}}</strong></td>
        <td><strong>{{i.3}}</strong></td>
        <td><strong>{{i.4}}</strong></td>
        
      </tr>
      {% endfor %}
    </table>
    
  </div>
  <div class="card-footer text-body-secondary">
    <form method="POST" action="{% url 'scrape:sts' %}">
      {% csrf_token %}
      <button type="submit" class="btn btn-outline-success">Push Request</button>
    </form>
    <form method="POST" action="{% url 'scrape:info' %}" style="float:left;">
      {% csrf_token %}
      <button type="submit" class="btn btn-outline-success">More Information</button>
    </form>
  </div>
</div>
<br>

<div class="ratio ratio-16x9" style="margin-left: 29%;
    height: 230pt;
    width: 42%;">
  {% for j in tohtml %}
  <iframe src="https://www.youtube.com/embed/{{j.5}}" title="YouTube video" allowfullscreen></iframe>
  {% endfor %}
</div>











{% comment %} <div class="container mt-4">
  <h1>Scraped Data</h1>
  <div class="container mt-4">
    <table class="table table-info table-striped">
      <tr>
        <td><strong>Title</strong></td>
        <td><strong>Likes</strong></td>
        <td><strong>Views</strong></td>
        <td><strong>Comments</strong></td>
        <td><strong>Subscribers</strong></td>
      </tr>
      {% for i in tohtml%}
      <tr>
        <td><strong>{{i.0}}</strong></td>
        <td><strong>{{i.1}}</strong></td>
        <td><strong>{{i.2}}</strong></td>
        <td><strong>{{i.3}}</strong></td>
        <td><strong>{{i.4}}</strong></td>
        
      </tr>
      {% endfor %}
    </table>
    {{ tohtml|safe }}
  </div>

  <form method="POST" action="{% url 'scrape:sts' %}">
    {% csrf_token %}
    <button type="submit" class="btn btn-outline-success">Push Request</button>
  </form>
</div> {% endcomment %}
{% endblock %}

scrape/templates/scrape/home.html
{% extends "scrape/main.html" %} {% block content %}
<div style="margin-left: 18%;
    margin-right: 18%;" class="card text-center">
  <div class="card-header">Youtube Video Link</div>
  <div class="card-body">
    <form method="POST" action="">
      {% csrf_token %}
      <div style="margin-left:26%;" class="input-group input-group-lg w-50">
        <input
          name="links"
          type="text"
          class="form-control"
          placeholder="Paste Your Link"
          aria-label="Recipient's username"
          aria-describedby="basic-addon2"
          required
        />
        
      </div>
      <br />
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    

  </div>
</div>

{% endblock %}

scrape/templates/scrape/main.html
<!doctype html>
<html lang="ar" dir="ltr">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.rtl.min.css" integrity="sha384-dpuaG1suU0eT09tx5plTaGMLBsfDLzUCCUXOY2j/LSvXYuG6Bqs43ALlhIqAJVRb" crossorigin="anonymous">
   
   
  </head>
  <body>
   <main>
      {% comment %} <div>
        <ul class="nav justify-content-end">
          {% if user.is_authenticated%}
             
            <li class="nav-item">
              <form action="{% url 'users:successl' %}" method='post'>
                 {% csrf_token %}
                 <button type='submit'>
                    Logout
                 </button>
              </form>
            </li>
          {%else%}
           <li class="nav-item">
              <form action="{%url 'users:login'%}">
                {% csrf_token %}
                <button type='submit'>
                   Login
                </button>
              </form>
            </li>

          {%endif%}
        </ul>
        
      </div> {% endcomment %}
      <nav style="margin-top: -8px;" class="navbar bg-body-tertiary fixed-top">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'scrape:home' %}"><h1><b>YT ARCHIVES</b></h1></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
            <div class="offcanvas-header">
              <h5 class="offcanvas-title" id="offcanvasNavbarLabel"></h5>
              <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
              <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'scrape:home'%}">Home</a>
                </li>
                <form method='post' action="{%url 'users:profile'%}" id='profileform'>
                  {% csrf_token %}
                  <li class="nav-item">
                    <a onclick="document.getElementById('profileform').submit(); return false;" class="nav-link" href="#" data-bs-toggle="modal" data-bs-target="#profileModal">Profile</a>
                  </li>
                </form>
                <form method='post' action="{%url 'users:Register'%}" id="registerform">
                  {% csrf_token %}
                  <li class="nav-item">
                    <a onclick="document.getElementById('registerform').submit();return false;" class="nav-link" href="#">Register</a>
                  </li>
                </form>
                {% if user.is_authenticated%}
                <form id='form' action="{% url 'users:successl' %}" method='post'>
                  {% csrf_token %}
                  <li class="nav-item">
                    <a onclick="document.getElementById('form').submit();return false;" class="nav-link" href="#">Logout</a>
                  </li>
                </form>
                {%else%}
                <form id='loginform' action="{%url 'users:login'%}">
                  {% csrf_token %}
                  <li class="nav-item">
                    <a onclick="document.getElementById('loginform').submit();return false;" class="nav-link" href="#">Login</a>
                  </li>
                </form>
                {%endif%}


              </ul>
              <form class="d-flex mt-3" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
              </form>
            </div>

          </div>
        </div>
      </nav>
      <br>
      
      <div class='w-50'>
           
           <input class="form-control" type="text" value="For DataAnalysis Purpose Only! TESTING PHASE" aria-label="Disabled input example" disabled readonly>
       </div>
      <div>
        <br>
       {% if messages %}
          {% for message in messages %}
             <div style="text-align: center;margin-left: 29%;margin-right: 29%;color:red;" class = 'alert alert-{{message.tags}}'>
              {{message}}
            </div>
          {%endfor%}
       {% endif %}
       
    </div><br>
    

      
    
       {% block content  %}
        

       {% endblock %} 
    </main>
   
    



   
    <script>
      document.addEventListener("DOMContentLoaded", function () {
          var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'));
          var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
              return new bootstrap.Tooltip(tooltipTriggerEl);
          });
      });
      </script>
      
   
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    
</html>

scrape/templates/scrape/success.html
{% extends "scrape/main.html" %} {% block content%}

<div class="card text-center">
  <div class="card-header">
    Notice
  </div>
  <div class="card-body">
    <h5 class="card-title">Special title treatment</h5>
    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
  <div class="card-footer text-body-secondary">
    2 days ago
  </div>
</div>

<form type="POST" action="{% url 'DB:dashboard' %}">
  <button type="submit" class="btn btn-outline-info">DashBoard</button>
  <br />
</form>
<form action="{% url 'scrape:home' %}">
  {% csrf_token %}
  <button
    onclick="window.location.href='{% url 'scrape:home' %}'"
    type="submit"
    class="btn btn-outline-info"
  >
    Home Page
  </button>
</form>

{% endblock %}